version: '{build}'

image: Visual Studio 2019

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
  - nuget restore src/Simplify.Web.sln

build:
  project: src/Simplify.Web.sln
  publish_nuget: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal
