name: Build Package

on: push

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install DotNet
        uses: actions/setup-dotnet@v1

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Package
        run: dotnet build --no-restore -c Release

      - name: Create Package
        run: dotnet pack --no-restore --no-build -c Release -o ./publish

      - name: Create packages artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./src/publish/
