name: Build Package

on: push

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            test-framework-command: --framework net8.0

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.1

      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Package
        run: dotnet build --no-restore -c Release

      - name: Perform Unit Testing
        run: dotnet test --no-build -c Release ${{ matrix.test-framework-command }} --verbosity normal --filter "TestCategory!=Benchmark"

      - name: Create Package
        run: dotnet pack Simplify.Web/Simplify.Web.csproj --no-build -c Release -o ./publish

      - name: Create packages artifact
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: ./src/publish/
